#!/usr/bin/env bash

# 🚀 YouTube 直播代理服务 - GitHub 推送完整指南

echo "╔═══════════════════════════════════════════════════════╗"
echo "║   YouTube 代理服务 - GitHub 推送指南                  ║"
echo "╚═══════════════════════════════════════════════════════╝"
echo ""

# ============================================================
# 选项 1: 最简单 - 在 VPS 上直接克隆（不需要推送）
# ============================================================

echo "📌 如果你不需要本地推送，可以在 VPS 上直接执行："
echo ""
echo "============ VPS 上执行 ============"
echo "bash <(curl -s https://raw.githubusercontent.com/klkanglang911/ytbnew/main/quick-deploy.sh)"
echo ""
echo "注意: 这需要你已将代码推送到 GitHub 上的 main 分支"
echo ""

# ============================================================
# 选项 2: 在本地推送代码到 GitHub
# ============================================================

echo "============================================================"
echo "方案 1: 使用 Personal Access Token (推荐)"
echo "============================================================"
echo ""
echo "Step 1: 生成 GitHub Personal Access Token"
echo "  • 访问 https://github.com/settings/tokens"
echo "  • 点击 'Generate new token'"
echo "  • 选择权限: repo (Full control of private repositories)"
echo "  • 复制生成的 Token (只显示一次)"
echo ""
echo "Step 2: 更新 Git 凭证"
echo "  运行命令（将 YOUR_TOKEN 替换为你的 Token）:"
echo ""
echo "  git remote set-url origin https://klkanglang911:YOUR_TOKEN@github.com/klkanglang911/ytbnew.git"
echo ""
echo "Step 3: 推送代码"
echo "  cd D:\\WORK\\AI_WORK\\ytb_new"
echo "  git push -u origin main"
echo ""

echo "============================================================"
echo "方案 2: 使用 SSH 密钥"
echo "============================================================"
echo ""
echo "Step 1: 生成 SSH 密钥 (如果还没有)"
echo "  ssh-keygen -t ed25519 -C 'klkanglang@gmail.com'"
echo "  按 Enter 三次使用默认设置"
echo ""
echo "Step 2: 添加 SSH 公钥到 GitHub"
echo "  • 复制 ~/.ssh/id_ed25519.pub 的内容"
echo "  • 访问 https://github.com/settings/keys"
echo "  • 点击 'New SSH key'"
echo "  • 粘贴公钥内容"
echo ""
echo "Step 3: 更新 Git 远程地址"
echo "  git remote set-url origin git@github.com:klkanglang911/ytbnew.git"
echo ""
echo "Step 4: 推送代码"
echo "  cd D:\\WORK\\AI_WORK\\ytb_new"
echo "  git push -u origin main"
echo ""

echo "============================================================"
echo "方案 3: 使用现有的自动化推送脚本"
echo "============================================================"
echo ""
echo "在 Windows 上选择以下之一:"
echo ""
echo "  • PowerShell (推荐):"
echo "    Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser"
echo "    D:\\WORK\\AI_WORK\\ytb_new\\push-to-github.ps1"
echo ""
echo "  • 批处理文件:"
echo "    D:\\WORK\\AI_WORK\\ytb_new\\push-to-github.bat"
echo ""

echo "============================================================"
echo "验证推送成功"
echo "============================================================"
echo ""
echo "推送完成后，运行以下命令验证:"
echo ""
echo "  git status              # 检查状态，应显示 'on branch main'"
echo "  git log --oneline -5   # 查看最近 5 个提交"
echo "  git branch -r           # 查看远程分支"
echo ""
echo "或访问 GitHub 网页:"
echo "  https://github.com/klkanglang911/ytbnew"
echo ""

echo "============================================================"
echo "推送到 GitHub 后的下一步"
echo "============================================================"
echo ""
echo "1️⃣  在 VPS 上克隆项目"
echo "    ssh root@your-vps-ip"
echo "    git clone https://github.com/klkanglang911/ytbnew.git"
echo "    cd ytbnew"
echo ""
echo "2️⃣  执行快速部署"
echo "    bash quick-deploy.sh"
echo ""
echo "    或完整命令:"
echo "    bash quick-deploy.sh ytb.yourdomain.com admin@domain.com https://webhook-url"
echo ""
echo "3️⃣  在本地 VLC 中导入 M3U 播放列表"
echo "    https://ytb.yourdomain.com/api/m3u"
echo ""

echo "============================================================"
echo "常见问题排查"
echo "============================================================"
echo ""
echo "❌ 错误: 'fatal: unable to access repository'"
echo "✓  解决: 检查 Token 是否正确，是否包含 repo 权限"
echo ""
echo "❌ 错误: 'Permission denied (publickey)'"
echo "✓  解决: SSH 密钥未配置或路径错误，使用 Token 方案"
echo ""
echo "❌ 错误: 'Authentication failed'"
echo "✓  解决: 重新生成 Token 并使用新的凭证"
echo ""
echo "❌ 错误: 'fatal: refusing to merge unrelated histories'"
echo "✓  解决: git pull --allow-unrelated-histories 或重新初始化"
echo ""

echo "============================================================"
echo "✓ 推送指南完成"
echo "============================================================"
echo ""
